// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "EX (SP),HL +            .tt" instead.

namespace IngameScript
{
    partial class Program
    {
        public partial class Z80InstructionExecutor
        {
            /// <summary>
            /// The EX (SP),HL instruction.
            /// </summary>
            byte EX_aSP_HL()
            {
                FetchFinished();

                var sp = (ushort)RG.SP;

                var temp = ReadShortFromMemory(sp);
                WriteShortToMemory(sp, RG.HL);
                RG.HL = temp;

                return 19;
            }

            /// <summary>
            /// The EX (SP),IX instruction.
            /// </summary>
            byte EX_aSP_IX()
            {
                FetchFinished();

                var sp = (ushort)RG.SP;

                var temp = ReadShortFromMemory(sp);
                WriteShortToMemory(sp, RG.IX);
                RG.IX = temp;

                return 23;
            }

            /// <summary>
            /// The EX (SP),IY instruction.
            /// </summary>
            byte EX_aSP_IY()
            {
                FetchFinished();

                var sp = (ushort)RG.SP;

                var temp = ReadShortFromMemory(sp);
                WriteShortToMemory(sp, RG.IY);
                RG.IY = temp;

                return 23;
            }
        }
    }
}