// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "JP (HL) +          .tt" instead.

namespace IngameScript
{
    partial class Program
    {
        public partial class Z80InstructionExecutor
        {
            /// <summary>
            /// The JP (HL) instruction.
            /// </summary>
            byte JP_aHL()
            {
                FetchFinished();

                RG.PC = (ushort)RG.HL;

                return 4;
            }

            /// <summary>
            /// The JP (IX) instruction.
            /// </summary>
            byte JP_aIX()
            {
                FetchFinished();

                RG.PC = (ushort)RG.IX;

                return 8;
            }

            /// <summary>
            /// The JP (IY) instruction.
            /// </summary>
            byte JP_aIY()
            {
                FetchFinished();

                RG.PC = (ushort)RG.IY;

                return 8;
            }
        }
    }
}