// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "LD (HL),n +        .tt" instead.

using System;

namespace IngameScript
{
    partial class Program
    {
        public partial class Z80InstructionExecutor
        {
            /// <summary>
            /// The LD (HL),n instruction.
            /// </summary>
            private byte LD_aHL_N()
            {
                var newValue = ProcessorAgent.FetchNextOpcode();
                FetchFinished();

                var address = (ushort)RG.HL;
                ProcessorAgent.WriteToMemory(address, newValue);

                return 10;
            }

            /// <summary>
            /// The LD (IX+n),n instruction.
            /// </summary>
            private byte LD_aIX_plus_n_N()
            {
                var offset = ProcessorAgent.FetchNextOpcode();
                var newValue = ProcessorAgent.FetchNextOpcode();
                FetchFinished();

                var address = (ushort)(RG.IX + (SByte)offset);
                ProcessorAgent.WriteToMemory(address, newValue);

                return 19;
            }

            /// <summary>
            /// The LD (IY+n),n instruction.
            /// </summary>
            private byte LD_aIY_plus_n_N()
            {
                var offset = ProcessorAgent.FetchNextOpcode();
                var newValue = ProcessorAgent.FetchNextOpcode();
                FetchFinished();

                var address = (ushort)(RG.IY + (SByte)offset);
                ProcessorAgent.WriteToMemory(address, newValue);

                return 19;
            }
        }
    }
}