// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "LD A,I +            .tt" instead.

namespace IngameScript
{
    partial class Program
    {
        public partial class Z80InstructionExecutor
        {
            /// <summary>
            /// The LD A,I instruction.
            /// </summary>
            byte LD_A_I()
            {
                FetchFinished();

                var value = RG.I;
                RG.A = value;

                RG.SF = GetBit(value, 7);
                RG.ZF = (value == 0);
                RG.HF = 0;
                RG.NF = 0;
                RG.PF = RG.IFF2;
                SetFlags3and5From(value);

                return 9;
            }

            /// <summary>
            /// The LD A,R instruction.
            /// </summary>
            byte LD_A_R()
            {
                FetchFinished();

                var value = RG.R;
                RG.A = value;

                RG.SF = GetBit(value, 7);
                RG.ZF = (value == 0);
                RG.HF = 0;
                RG.NF = 0;
                RG.PF = RG.IFF2;
                SetFlags3and5From(value);

                return 9;
            }
        }
    }
}