// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "LD I,A +            .tt" instead.

namespace IngameScript
{
    partial class Program
    {
        public partial class Z80InstructionExecutor
        {
            /// <summary>
            /// The LD I,A instruction.
            /// </summary>
            byte LD_I_A()
            {
                FetchFinished();

                RG.I = RG.A;

                return 9;
            }

            /// <summary>
            /// The LD R,A instruction.
            /// </summary>
            byte LD_R_A()
            {
                FetchFinished();

                RG.R = RG.A;

                return 9;
            }
        }
    }
}