// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "LD r,r       .tt" instead.


namespace IngameScript
{
    partial class Program
    {
        public partial class Z80InstructionExecutor
        {
            /// <summary>
            /// The LD A,A instruction.
            /// </summary>
            byte LD_A_A()
            {
                FetchFinished();

                return 4;
            }

            /// <summary>
            /// The LD B,A instruction.
            /// </summary>
            byte LD_B_A()
            {
                FetchFinished();

                RG.B = RG.A;

                return 4;
            }

            /// <summary>
            /// The LD C,A instruction.
            /// </summary>
            byte LD_C_A()
            {
                FetchFinished();

                RG.C = RG.A;

                return 4;
            }

            /// <summary>
            /// The LD D,A instruction.
            /// </summary>
            byte LD_D_A()
            {
                FetchFinished();

                RG.D = RG.A;

                return 4;
            }

            /// <summary>
            /// The LD E,A instruction.
            /// </summary>
            byte LD_E_A()
            {
                FetchFinished();

                RG.E = RG.A;

                return 4;
            }

            /// <summary>
            /// The LD H,A instruction.
            /// </summary>
            byte LD_H_A()
            {
                FetchFinished();

                RG.H = RG.A;

                return 4;
            }

            /// <summary>
            /// The LD L,A instruction.
            /// </summary>
            byte LD_L_A()
            {
                FetchFinished();

                RG.L = RG.A;

                return 4;
            }

            /// <summary>
            /// The LD IXH,A instruction.
            /// </summary>
            byte LD_IXH_A()
            {
                FetchFinished();

                RG.IXH = RG.A;

                return 8;
            }

            /// <summary>
            /// The LD IXL,A instruction.
            /// </summary>
            byte LD_IXL_A()
            {
                FetchFinished();

                RG.IXL = RG.A;

                return 8;
            }

            /// <summary>
            /// The LD IYH,A instruction.
            /// </summary>
            byte LD_IYH_A()
            {
                FetchFinished();

                RG.IYH = RG.A;

                return 8;
            }

            /// <summary>
            /// The LD IYL,A instruction.
            /// </summary>
            byte LD_IYL_A()
            {
                FetchFinished();

                RG.IYL = RG.A;

                return 8;
            }

            /// <summary>
            /// The LD A,B instruction.
            /// </summary>
            byte LD_A_B()
            {
                FetchFinished();

                RG.A = RG.B;

                return 4;
            }

            /// <summary>
            /// The LD B,B instruction.
            /// </summary>
            byte LD_B_B()
            {
                FetchFinished();

                return 4;
            }

            /// <summary>
            /// The LD C,B instruction.
            /// </summary>
            byte LD_C_B()
            {
                FetchFinished();

                RG.C = RG.B;

                return 4;
            }

            /// <summary>
            /// The LD D,B instruction.
            /// </summary>
            byte LD_D_B()
            {
                FetchFinished();

                RG.D = RG.B;

                return 4;
            }

            /// <summary>
            /// The LD E,B instruction.
            /// </summary>
            byte LD_E_B()
            {
                FetchFinished();

                RG.E = RG.B;

                return 4;
            }

            /// <summary>
            /// The LD H,B instruction.
            /// </summary>
            byte LD_H_B()
            {
                FetchFinished();

                RG.H = RG.B;

                return 4;
            }

            /// <summary>
            /// The LD L,B instruction.
            /// </summary>
            byte LD_L_B()
            {
                FetchFinished();

                RG.L = RG.B;

                return 4;
            }

            /// <summary>
            /// The LD IXH,B instruction.
            /// </summary>
            byte LD_IXH_B()
            {
                FetchFinished();

                RG.IXH = RG.B;

                return 8;
            }

            /// <summary>
            /// The LD IXL,B instruction.
            /// </summary>
            byte LD_IXL_B()
            {
                FetchFinished();

                RG.IXL = RG.B;

                return 8;
            }

            /// <summary>
            /// The LD IYH,B instruction.
            /// </summary>
            byte LD_IYH_B()
            {
                FetchFinished();

                RG.IYH = RG.B;

                return 8;
            }

            /// <summary>
            /// The LD IYL,B instruction.
            /// </summary>
            byte LD_IYL_B()
            {
                FetchFinished();

                RG.IYL = RG.B;

                return 8;
            }

            /// <summary>
            /// The LD A,C instruction.
            /// </summary>
            byte LD_A_C()
            {
                FetchFinished();

                RG.A = RG.C;

                return 4;
            }

            /// <summary>
            /// The LD B,C instruction.
            /// </summary>
            byte LD_B_C()
            {
                FetchFinished();

                RG.B = RG.C;

                return 4;
            }

            /// <summary>
            /// The LD C,C instruction.
            /// </summary>
            byte LD_C_C()
            {
                FetchFinished();

                return 4;
            }

            /// <summary>
            /// The LD D,C instruction.
            /// </summary>
            byte LD_D_C()
            {
                FetchFinished();

                RG.D = RG.C;

                return 4;
            }

            /// <summary>
            /// The LD E,C instruction.
            /// </summary>
            byte LD_E_C()
            {
                FetchFinished();

                RG.E = RG.C;

                return 4;
            }

            /// <summary>
            /// The LD H,C instruction.
            /// </summary>
            byte LD_H_C()
            {
                FetchFinished();

                RG.H = RG.C;

                return 4;
            }

            /// <summary>
            /// The LD L,C instruction.
            /// </summary>
            byte LD_L_C()
            {
                FetchFinished();

                RG.L = RG.C;

                return 4;
            }

            /// <summary>
            /// The LD IXH,C instruction.
            /// </summary>
            byte LD_IXH_C()
            {
                FetchFinished();

                RG.IXH = RG.C;

                return 8;
            }

            /// <summary>
            /// The LD IXL,C instruction.
            /// </summary>
            byte LD_IXL_C()
            {
                FetchFinished();

                RG.IXL = RG.C;

                return 8;
            }

            /// <summary>
            /// The LD IYH,C instruction.
            /// </summary>
            byte LD_IYH_C()
            {
                FetchFinished();

                RG.IYH = RG.C;

                return 8;
            }

            /// <summary>
            /// The LD IYL,C instruction.
            /// </summary>
            byte LD_IYL_C()
            {
                FetchFinished();

                RG.IYL = RG.C;

                return 8;
            }

            /// <summary>
            /// The LD A,D instruction.
            /// </summary>
            byte LD_A_D()
            {
                FetchFinished();

                RG.A = RG.D;

                return 4;
            }

            /// <summary>
            /// The LD B,D instruction.
            /// </summary>
            byte LD_B_D()
            {
                FetchFinished();

                RG.B = RG.D;

                return 4;
            }

            /// <summary>
            /// The LD C,D instruction.
            /// </summary>
            byte LD_C_D()
            {
                FetchFinished();

                RG.C = RG.D;

                return 4;
            }

            /// <summary>
            /// The LD D,D instruction.
            /// </summary>
            byte LD_D_D()
            {
                FetchFinished();

                return 4;
            }

            /// <summary>
            /// The LD E,D instruction.
            /// </summary>
            byte LD_E_D()
            {
                FetchFinished();

                RG.E = RG.D;

                return 4;
            }

            /// <summary>
            /// The LD H,D instruction.
            /// </summary>
            byte LD_H_D()
            {
                FetchFinished();

                RG.H = RG.D;

                return 4;
            }

            /// <summary>
            /// The LD L,D instruction.
            /// </summary>
            byte LD_L_D()
            {
                FetchFinished();

                RG.L = RG.D;

                return 4;
            }

            /// <summary>
            /// The LD IXH,D instruction.
            /// </summary>
            byte LD_IXH_D()
            {
                FetchFinished();

                RG.IXH = RG.D;

                return 8;
            }

            /// <summary>
            /// The LD IXL,D instruction.
            /// </summary>
            byte LD_IXL_D()
            {
                FetchFinished();

                RG.IXL = RG.D;

                return 8;
            }

            /// <summary>
            /// The LD IYH,D instruction.
            /// </summary>
            byte LD_IYH_D()
            {
                FetchFinished();

                RG.IYH = RG.D;

                return 8;
            }

            /// <summary>
            /// The LD IYL,D instruction.
            /// </summary>
            byte LD_IYL_D()
            {
                FetchFinished();

                RG.IYL = RG.D;

                return 8;
            }

            /// <summary>
            /// The LD A,E instruction.
            /// </summary>
            byte LD_A_E()
            {
                FetchFinished();

                RG.A = RG.E;

                return 4;
            }

            /// <summary>
            /// The LD B,E instruction.
            /// </summary>
            byte LD_B_E()
            {
                FetchFinished();

                RG.B = RG.E;

                return 4;
            }

            /// <summary>
            /// The LD C,E instruction.
            /// </summary>
            byte LD_C_E()
            {
                FetchFinished();

                RG.C = RG.E;

                return 4;
            }

            /// <summary>
            /// The LD D,E instruction.
            /// </summary>
            byte LD_D_E()
            {
                FetchFinished();

                RG.D = RG.E;

                return 4;
            }

            /// <summary>
            /// The LD E,E instruction.
            /// </summary>
            byte LD_E_E()
            {
                FetchFinished();

                return 4;
            }

            /// <summary>
            /// The LD H,E instruction.
            /// </summary>
            byte LD_H_E()
            {
                FetchFinished();

                RG.H = RG.E;

                return 4;
            }

            /// <summary>
            /// The LD L,E instruction.
            /// </summary>
            byte LD_L_E()
            {
                FetchFinished();

                RG.L = RG.E;

                return 4;
            }

            /// <summary>
            /// The LD IXH,E instruction.
            /// </summary>
            byte LD_IXH_E()
            {
                FetchFinished();

                RG.IXH = RG.E;

                return 8;
            }

            /// <summary>
            /// The LD IXL,E instruction.
            /// </summary>
            byte LD_IXL_E()
            {
                FetchFinished();

                RG.IXL = RG.E;

                return 8;
            }

            /// <summary>
            /// The LD IYH,E instruction.
            /// </summary>
            byte LD_IYH_E()
            {
                FetchFinished();

                RG.IYH = RG.E;

                return 8;
            }

            /// <summary>
            /// The LD IYL,E instruction.
            /// </summary>
            byte LD_IYL_E()
            {
                FetchFinished();

                RG.IYL = RG.E;

                return 8;
            }

            /// <summary>
            /// The LD A,H instruction.
            /// </summary>
            byte LD_A_H()
            {
                FetchFinished();

                RG.A = RG.H;

                return 4;
            }

            /// <summary>
            /// The LD B,H instruction.
            /// </summary>
            byte LD_B_H()
            {
                FetchFinished();

                RG.B = RG.H;

                return 4;
            }

            /// <summary>
            /// The LD C,H instruction.
            /// </summary>
            byte LD_C_H()
            {
                FetchFinished();

                RG.C = RG.H;

                return 4;
            }

            /// <summary>
            /// The LD D,H instruction.
            /// </summary>
            byte LD_D_H()
            {
                FetchFinished();

                RG.D = RG.H;

                return 4;
            }

            /// <summary>
            /// The LD E,H instruction.
            /// </summary>
            byte LD_E_H()
            {
                FetchFinished();

                RG.E = RG.H;

                return 4;
            }

            /// <summary>
            /// The LD H,H instruction.
            /// </summary>
            byte LD_H_H()
            {
                FetchFinished();

                return 4;
            }

            /// <summary>
            /// The LD L,H instruction.
            /// </summary>
            byte LD_L_H()
            {
                FetchFinished();

                RG.L = RG.H;

                return 4;
            }

            /// <summary>
            /// The LD IXH,H instruction.
            /// </summary>
            byte LD_IXH_H()
            {
                FetchFinished();

                RG.IXH = RG.H;

                return 8;
            }

            /// <summary>
            /// The LD IXL,H instruction.
            /// </summary>
            byte LD_IXL_H()
            {
                FetchFinished();

                RG.IXL = RG.H;

                return 8;
            }

            /// <summary>
            /// The LD IYL,H instruction.
            /// </summary>
            byte LD_IYL_H()
            {
                FetchFinished();

                RG.IYL = RG.H;

                return 8;
            }

            /// <summary>
            /// The LD A,L instruction.
            /// </summary>
            byte LD_A_L()
            {
                FetchFinished();

                RG.A = RG.L;

                return 4;
            }

            /// <summary>
            /// The LD B,L instruction.
            /// </summary>
            byte LD_B_L()
            {
                FetchFinished();

                RG.B = RG.L;

                return 4;
            }

            /// <summary>
            /// The LD C,L instruction.
            /// </summary>
            byte LD_C_L()
            {
                FetchFinished();

                RG.C = RG.L;

                return 4;
            }

            /// <summary>
            /// The LD D,L instruction.
            /// </summary>
            byte LD_D_L()
            {
                FetchFinished();

                RG.D = RG.L;

                return 4;
            }

            /// <summary>
            /// The LD E,L instruction.
            /// </summary>
            byte LD_E_L()
            {
                FetchFinished();

                RG.E = RG.L;

                return 4;
            }

            /// <summary>
            /// The LD H,L instruction.
            /// </summary>
            byte LD_H_L()
            {
                FetchFinished();

                RG.H = RG.L;

                return 4;
            }

            /// <summary>
            /// The LD L,L instruction.
            /// </summary>
            byte LD_L_L()
            {
                FetchFinished();

                return 4;
            }

            /// <summary>
            /// The LD A,IXH instruction.
            /// </summary>
            byte LD_A_IXH()
            {
                FetchFinished();

                RG.A = RG.IXH;

                return 8;
            }

            /// <summary>
            /// The LD B,IXH instruction.
            /// </summary>
            byte LD_B_IXH()
            {
                FetchFinished();

                RG.B = RG.IXH;

                return 8;
            }

            /// <summary>
            /// The LD C,IXH instruction.
            /// </summary>
            byte LD_C_IXH()
            {
                FetchFinished();

                RG.C = RG.IXH;

                return 8;
            }

            /// <summary>
            /// The LD D,IXH instruction.
            /// </summary>
            byte LD_D_IXH()
            {
                FetchFinished();

                RG.D = RG.IXH;

                return 8;
            }

            /// <summary>
            /// The LD E,IXH instruction.
            /// </summary>
            byte LD_E_IXH()
            {
                FetchFinished();

                RG.E = RG.IXH;

                return 8;
            }

            /// <summary>
            /// The LD IXH,IXH instruction.
            /// </summary>
            byte LD_IXH_IXH()
            {
                FetchFinished();

                return 8;
            }

            /// <summary>
            /// The LD A,IXL instruction.
            /// </summary>
            byte LD_A_IXL()
            {
                FetchFinished();

                RG.A = RG.IXL;

                return 8;
            }

            /// <summary>
            /// The LD B,IXL instruction.
            /// </summary>
            byte LD_B_IXL()
            {
                FetchFinished();

                RG.B = RG.IXL;

                return 8;
            }

            /// <summary>
            /// The LD C,IXL instruction.
            /// </summary>
            byte LD_C_IXL()
            {
                FetchFinished();

                RG.C = RG.IXL;

                return 8;
            }

            /// <summary>
            /// The LD D,IXL instruction.
            /// </summary>
            byte LD_D_IXL()
            {
                FetchFinished();

                RG.D = RG.IXL;

                return 8;
            }

            /// <summary>
            /// The LD E,IXL instruction.
            /// </summary>
            byte LD_E_IXL()
            {
                FetchFinished();

                RG.E = RG.IXL;

                return 8;
            }

            /// <summary>
            /// The LD IXH,IXL instruction.
            /// </summary>
            byte LD_IXH_IXL()
            {
                FetchFinished();

                RG.IXH = RG.IXL;

                return 8;
            }

            /// <summary>
            /// The LD IXL,IXL instruction.
            /// </summary>
            byte LD_IXL_IXL()
            {
                FetchFinished();

                return 8;
            }

            /// <summary>
            /// The LD A,IYH instruction.
            /// </summary>
            byte LD_A_IYH()
            {
                FetchFinished();

                RG.A = RG.IYH;

                return 8;
            }

            /// <summary>
            /// The LD B,IYH instruction.
            /// </summary>
            byte LD_B_IYH()
            {
                FetchFinished();

                RG.B = RG.IYH;

                return 8;
            }

            /// <summary>
            /// The LD C,IYH instruction.
            /// </summary>
            byte LD_C_IYH()
            {
                FetchFinished();

                RG.C = RG.IYH;

                return 8;
            }

            /// <summary>
            /// The LD D,IYH instruction.
            /// </summary>
            byte LD_D_IYH()
            {
                FetchFinished();

                RG.D = RG.IYH;

                return 8;
            }

            /// <summary>
            /// The LD E,IYH instruction.
            /// </summary>
            byte LD_E_IYH()
            {
                FetchFinished();

                RG.E = RG.IYH;

                return 8;
            }

            /// <summary>
            /// The LD IYH,IYH instruction.
            /// </summary>
            byte LD_IYH_IYH()
            {
                FetchFinished();

                return 8;
            }

            /// <summary>
            /// The LD A,IYL instruction.
            /// </summary>
            byte LD_A_IYL()
            {
                FetchFinished();

                RG.A = RG.IYL;

                return 8;
            }

            /// <summary>
            /// The LD B,IYL instruction.
            /// </summary>
            byte LD_B_IYL()
            {
                FetchFinished();

                RG.B = RG.IYL;

                return 8;
            }

            /// <summary>
            /// The LD C,IYL instruction.
            /// </summary>
            byte LD_C_IYL()
            {
                FetchFinished();

                RG.C = RG.IYL;

                return 8;
            }

            /// <summary>
            /// The LD D,IYL instruction.
            /// </summary>
            byte LD_D_IYL()
            {
                FetchFinished();

                RG.D = RG.IYL;

                return 8;
            }

            /// <summary>
            /// The LD E,IYL instruction.
            /// </summary>
            byte LD_E_IYL()
            {
                FetchFinished();

                RG.E = RG.IYL;

                return 8;
            }

            /// <summary>
            /// The LD IYH,IYL instruction.
            /// </summary>
            byte LD_IYH_IYL()
            {
                FetchFinished();

                RG.IYH = RG.IYL;

                return 8;
            }

            /// <summary>
            /// The LD IYL,IYL instruction.
            /// </summary>
            byte LD_IYL_IYL()
            {
                FetchFinished();

                return 8;
            }
        }
    }
}