// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "LD SP,HL +         .tt" instead.

namespace IngameScript
{
    partial class Program
    {
        public partial class Z80InstructionExecutor
        {
            /// <summary>
            /// The LD SP,HL instruction.
            /// </summary>
            byte LD_SP_HL()
            {
                FetchFinished(isLdSp: true);

                RG.SP = RG.HL;

                return 6;
            }

            /// <summary>
            /// The LD SP,IX instruction.
            /// </summary>
            byte LD_SP_IX()
            {
                FetchFinished(isLdSp: true);

                RG.SP = RG.IX;

                return 10;
            }

            /// <summary>
            /// The LD SP,IY instruction.
            /// </summary>
            byte LD_SP_IY()
            {
                FetchFinished(isLdSp: true);

                RG.SP = RG.IY;

                return 10;
            }
        }
    }
}