// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "OUT (C),r            .tt" instead.

namespace IngameScript
{
    partial class Program
    {
        public partial class Z80InstructionExecutor
        {
            /// <summary>
            /// The OUT (C),A instruction.
            /// </summary>
            byte OUT_C_A()
            {
                FetchFinished();

                ProcessorAgent.WriteToPort(RG.C, RG.A);

                return 12;
            }

            /// <summary>
            /// The OUT (C),B instruction.
            /// </summary>
            byte OUT_C_B()
            {
                FetchFinished();

                ProcessorAgent.WriteToPort(RG.C, RG.B);

                return 12;
            }

            /// <summary>
            /// The OUT (C),C instruction.
            /// </summary>
            byte OUT_C_C()
            {
                FetchFinished();

                ProcessorAgent.WriteToPort(RG.C, RG.C);

                return 12;
            }

            /// <summary>
            /// The OUT (C),D instruction.
            /// </summary>
            byte OUT_C_D()
            {
                FetchFinished();

                ProcessorAgent.WriteToPort(RG.C, RG.D);

                return 12;
            }

            /// <summary>
            /// The OUT (C),E instruction.
            /// </summary>
            byte OUT_C_E()
            {
                FetchFinished();

                ProcessorAgent.WriteToPort(RG.C, RG.E);

                return 12;
            }

            /// <summary>
            /// The OUT (C),H instruction.
            /// </summary>
            byte OUT_C_H()
            {
                FetchFinished();

                ProcessorAgent.WriteToPort(RG.C, RG.H);

                return 12;
            }

            /// <summary>
            /// The OUT (C),L instruction.
            /// </summary>
            byte OUT_C_L()
            {
                FetchFinished();

                ProcessorAgent.WriteToPort(RG.C, RG.L);

                return 12;
            }

            /// <summary>
            /// The OUT (C),0 instruction.
            /// </summary>
            byte OUT_C_0()
            {
                FetchFinished();

                ProcessorAgent.WriteToPort(RG.C, 0);

                return 12;
            }
        }
    }
}